# Generated by Django 3.0.8 on 2020-07-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=70)),
                ('idade', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
